"""ahahahahahaaaa

Revision ID: 42c74b81121b
Revises: 1c009f0136d5
Create Date: 2023-06-15 01:08:07.965445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c74b81121b'
down_revision = '1c009f0136d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
